on:
  - push

jobs:
  code_formatting:
    name: Code Formatting
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          elixir-version: 1.10.2
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check code formatting
        run: mix format --check-formatted

  type_check:
    name: Type Check
    runs-on: ubuntu-18.04
    env:
      MIX_TARGET: keybow
    steps:
      - name: Set up Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: 22.3
          elixir-version: 1.10.2
      - name: Install Nerves bootstrap
        run: mix archive.install --force hex nerves_bootstrap
      - name: Restore Nerves artifacts
        uses: actions/cache@v1
        with:
          path: ~/.nerves/artifacts
          key: nerves-artifacts-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            nerves-artifacts-${{ github.ref }}-${{ github.sha }}
            nerves-artifacts-${{ github.ref }}-
            nerves-artifacts-refs/heads/master-
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Get dependencies
        run: mix deps.get
      - name: Restore PLTs
        uses: actions/cache@v1
        with:
          path: _build/${{ env.MIX_TARGET }}_dev/plt
          key: plt-${{ github.ref }}-${{ github.sha }}
          restore-keys: |
            plt-${{ github.ref }}-${{ github.sha }}
            plt-${{ github.ref }}-
            plt-refs/heads/master-
      - name: Compile
        run: mix compile
      - name: Run dialyzer
        run: mix dialyzer
